library wallet_core_bindings;

import 'package:fixnum/fixnum.dart';
import 'package:protobuf/protobuf.dart';
import 'proto/Aion.pb.dart' as $aion;
import 'proto/Binance.pb.dart' as $binance;
import 'proto/Bitcoin.pb.dart' as $bitcoin;
import 'proto/Cosmos.pb.dart' as $cosmos;
import 'proto/Ethereum.pb.dart' as $ethereum;
import 'proto/Tezos.pb.dart' as $tezos;
import 'proto/Tron.pb.dart' as $tron;
import 'proto/Icon.pb.dart' as $icon;
import 'proto/Nimiq.pb.dart' as $nimiq;
import 'proto/Ripple.pb.dart' as $ripple;
import 'proto/Stellar.pb.dart' as $stellar;
import 'proto/VeChain.pb.dart' as $ve_chain;
import 'proto/Theta.pb.dart' as $theta;
import 'proto/Ontology.pb.dart' as $ontology;
import 'proto/Zilliqa.pb.dart' as $zilliqa;
import 'proto/IoTeX.pb.dart' as $io_te_x;
import 'proto/EOS.pb.dart' as $eos;
import 'proto/Nano.pb.dart' as $nano;
import 'proto/NULS.pb.dart' as $nuls;
import 'proto/Waves.pb.dart' as $waves;
import 'proto/Aeternity.pb.dart' as $aeternity;
import 'proto/Nebulas.pb.dart' as $nebulas;
import 'proto/FIO.pb.dart' as $fio;
import 'proto/Solana.pb.dart' as $solana;
import 'proto/Harmony.pb.dart' as $harmony;
import 'proto/NEAR.pb.dart' as $near;
import 'proto/Algorand.pb.dart' as $algorand;
import 'proto/IOST.pb.dart' as $iost;
import 'proto/Polkadot.pb.dart' as $polkadot;
import 'proto/Cardano.pb.dart' as $cardano;
import 'proto/NEO.pb.dart' as $neo;
import 'proto/Filecoin.pb.dart' as $filecoin;
import 'proto/MultiversX.pb.dart' as $multivers_x;
import 'proto/Oasis.pb.dart' as $oasis;
import 'proto/Decred.pb.dart' as $decred;
import 'proto/Nervos.pb.dart' as $nervos;
import 'proto/Everscale.pb.dart' as $everscale;
import 'proto/Aptos.pb.dart' as $aptos;
import 'proto/Hedera.pb.dart' as $hedera;
import 'proto/TheOpenNetwork.pb.dart' as $the_open_network;
import 'proto/Sui.pb.dart' as $sui;
import 'proto/Greenfield.pb.dart' as $greenfield;
import 'proto/InternetComputer.pb.dart' as $internet_computer;
import 'proto/Pactus.pb.dart' as $pactus;
import 'proto/TransactionCompiler.pb.dart' as $transaction_compiler;
import 'package:wallet_core_bindings/proto/Polymesh.pb.dart' as $polymesh;

import 'ffi/finalizable.dart' if (dart.library.io) 'dart:ffi';
import 'dart:typed_data';

part 'src/tw_account.dart';
part 'src/tw_aes.dart';
part 'src/tw_aes_padding_mode.dart';
part 'src/tw_any_address.dart';
part 'src/tw_any_signer.dart';
part 'src/tw_asn_parser.dart';
part 'src/tw_barz.dart';
part 'src/tw_biz.dart';
part 'src/tw_biz_passkey_session.dart';
part 'src/tw_base32.dart';
part 'src/tw_base58.dart';
part 'src/tw_base64.dart';
part 'src/tw_bech32.dart';
part 'src/tw_bitcoin_address.dart';
part 'src/tw_bitcoin_message_signer.dart';
part 'src/tw_bitcoin_script.dart';
part 'src/tw_bitcoin_sig_hash_type.dart';
part 'src/tw_blockchain.dart';
part 'src/tw_cardano.dart';
part 'src/tw_coin_type.dart';
part 'src/tw_coin_type_configuration.dart';
part 'src/tw_crypto_box.dart';
part 'src/tw_crypto_box_public_key.dart';
part 'src/tw_crypto_box_secret_key.dart';
part 'src/tw_curve.dart';
part 'src/tw_data.dart';
part 'src/tw_data_vector.dart';
part 'src/tw_derivation.dart';
part 'src/tw_derivation_path.dart';
part 'src/tw_derivation_path_index.dart';
part 'src/tw_eip7702.dart';
part 'src/tw_ethereum.dart';
part 'src/tw_ethereum_abi.dart';
part 'src/tw_ethereum_abi_function.dart';
part 'src/tw_ethereum_abi_value.dart';
part 'src/tw_ethereum_chain_id.dart';
part 'src/tw_ethereum_message_signer.dart';
part 'src/tw_ethereum_rlp.dart';
part 'src/tw_filecoin_address_converter.dart';
part 'src/tw_fio_account.dart';
part 'src/tw_firo_address_type.dart';
part 'src/tw_groestlcoin_address.dart';
part 'src/tw_filecoin_address_type.dart';
part 'src/tw_hash.dart';
part 'src/tw_hd_version.dart';
part 'src/tw_hd_wallet.dart';
part 'src/tw_hrp.dart';
part 'src/tw_liquid_staking.dart';
part 'src/tw_message_signer.dart';
part 'src/tw_mnemonic.dart';
part 'src/tw_near_account.dart';
part 'src/tw_nervos_address.dart';
part 'src/tw_pbkdf2.dart';
part 'src/tw_object.dart';
part 'src/tw_private_key.dart';
part 'src/tw_private_key_type.dart';
part 'src/tw_public_key.dart';
part 'src/tw_public_key_type.dart';
part 'src/tw_purpose.dart';
part 'src/tw_segwit_address.dart';
part 'src/tw_solana_address.dart';
part 'src/tw_solana_transaction.dart';
part 'src/tw_stark_ex_message_signer.dart';
part 'src/tw_stark_ware.dart';
part 'src/tw_stellar_memo_type.dart';
part 'src/tw_stellar_passphrase.dart';
part 'src/tw_stellar_version_byte.dart';
part 'src/tw_stored_key.dart';
part 'src/tw_stored_key_encryption.dart';
part 'src/tw_stored_key_encryption_level.dart';
part 'src/tw_string.dart';
part 'src/tw_tezos_message_signer.dart';
part 'src/tw_thor_chain_swap.dart';
part 'src/tw_ton_address_converter.dart';
part 'src/tw_ton_message_signer.dart';
part 'src/tw_ton_wallet.dart';
part 'src/tw_transaction_compiler.dart';
part 'src/tw_transaction_decoder.dart';
part 'src/tw_transaction_util.dart';
part 'src/tw_tron_message_signer.dart';
part 'src/tw_wallet_connect_request.dart';
part 'src/tw_web_authn.dart';
part 'src/tw_web_authn_solidity.dart';
part 'src/interface/wallet_core_bindings_interface.dart';
part 'src/interface/tw_account_interface.dart';
part 'src/interface/tw_aes_interface.dart';
part 'src/interface/tw_any_address_interface.dart';
part 'src/interface/tw_any_signer_interface.dart';
part 'src/interface/tw_asn_parser_interface.dart';
part 'src/interface/tw_barz_interface.dart';
part 'src/interface/tw_biz_interface.dart';
part 'src/interface/tw_biz_passkey_session_interface.dart';
part 'src/interface/tw_base32_interface.dart';
part 'src/interface/tw_base58_interface.dart';
part 'src/interface/tw_base64_interface.dart';
part 'src/interface/tw_bech32_interface.dart';
part 'src/interface/tw_bitcoin_address_interface.dart';
part 'src/interface/tw_bitcoin_message_signer_interface.dart';
part 'src/interface/tw_bitcoin_script_interface.dart';
part 'src/interface/tw_bitcoin_sig_hash_type_interface.dart';
part 'src/interface/tw_cardano_interface.dart';
part 'src/interface/tw_coin_type_configuration_interface.dart';
part 'src/interface/tw_coin_type_interface.dart';
part 'src/interface/tw_crypto_box_interface.dart';
part 'src/interface/tw_crypto_box_public_key_interface.dart';
part 'src/interface/tw_crypto_box_secret_key_interface.dart';
part 'src/interface/tw_data_interface.dart';
part 'src/interface/tw_data_vector_interface.dart';
part 'src/interface/tw_derivation_path_interface.dart';
part 'src/interface/tw_derivation_path_index_interface.dart';
part 'src/interface/tw_eip7702_interface.dart';
part 'src/interface/tw_ethereum_interface.dart';
part 'src/interface/tw_ethereum_abi_interface.dart';
part 'src/interface/tw_ethereum_abi_function_interface.dart';
part 'src/interface/tw_ethereum_abi_value_interface.dart';
part 'src/interface/tw_ethereum_message_signer_interface.dart';
part 'src/interface/tw_ethereum_rlp_interface.dart';
part 'src/interface/tw_filecoin_address_converter_interface.dart';
part 'src/interface/tw_fio_account_interface.dart';
part 'src/interface/tw_groestlcoin_address_interface.dart';
part 'src/interface/tw_hash_interface.dart';
part 'src/interface/tw_hd_wallet_interface.dart';
part 'src/interface/tw_hd_version_interface.dart';
part 'src/interface/tw_hrp_interface.dart';
part 'src/interface/tw_liquid_staking_interface.dart';
part 'src/interface/tw_message_signer_interface.dart';
part 'src/interface/tw_mnemonic_interface.dart';
part 'src/interface/tw_near_account_interface.dart';
part 'src/interface/tw_nervos_address_interface.dart';
part 'src/interface/tw_pbkdf2_interface.dart';
part 'src/interface/tw_private_key_interface.dart';
part 'src/interface/tw_public_key_interface.dart';
part 'src/interface/tw_segwit_address_interface.dart';
part 'src/interface/tw_solana_address_interface.dart';
part 'src/interface/tw_solana_transaction_interface.dart';
part 'src/interface/tw_stark_ex_message_signer_interface.dart';
part 'src/interface/tw_stark_ware_interface.dart';
part 'src/interface/tw_stored_key_interface.dart';
part 'src/interface/tw_string_interface.dart';
part 'src/interface/tw_tezos_message_signer_interface.dart';
part 'src/interface/tw_thor_chain_swap_interface.dart';
part 'src/interface/tw_ton_address_converter_interface.dart';
part 'src/interface/tw_ton_message_signer_interface.dart';
part 'src/interface/tw_ton_wallet_interface.dart';
part 'src/interface/tw_transaction_compiler_interface.dart';
part 'src/interface/tw_transaction_decoder_interface.dart';
part 'src/interface/tw_transaction_util_interface.dart';
part 'src/interface/tw_tron_message_signer_interface.dart';
part 'src/interface/tw_wallet_connect_request_interface.dart';
part 'src/interface/tw_web_authn_interface.dart';
part 'src/interface/tw_web_authn_solidity_interface.dart';
part 'src/exception/tw_exception.dart';
part 'src/extension/tw_any_sign_extension.dart';
part 'src/extension/tw_bigint_extension.dart';
part 'src/extension/tw_int_extension.dart';
part 'src/extension/tw_string_extension.dart';
part 'src/extension/tw_pre_image_hashes_extension.dart';
part 'src/extension/aion/tw_aion_extension.dart';
part 'src/extension/binance/tw_binance_extension.dart';
part 'src/extension/bitcoin/tw_bitcoin_extension.dart';
part 'src/extension/cosmos/tw_cosmos_extension.dart';
part 'src/extension/ethereum/tw_ethereum_extension.dart';
part 'src/extension/icon/tw_icon_extension.dart';
part 'src/extension/nimiq/tw_nimiq_extension.dart';
part 'src/extension/tezos/tw_tezos_extension.dart';
part 'src/extension/tron/tw_tron_extension.dart';
part 'src/extension/ripple/tw_ripple_extension.dart';
part 'src/extension/stellar/tw_stellar_extension.dart';
part 'src/extension/vechain/tw_ve_chain_extension.dart';
part 'src/extension/theta/tw_theta_extension.dart';
part 'src/extension/ontology/tw_ontology_extension.dart';
part 'src/extension/zilliqa/tw_zilliqa_extension.dart';
part 'src/extension/iost/tw_iost_extension.dart';
part 'src/extension/io_te_x/tw_io_te_x_extension.dart';
part 'src/extension/eos/tw_eos_extension.dart';
part 'src/extension/nano/tw_nano_extension.dart';
part 'src/extension/nuls/tw_nuls_extension.dart';
part 'src/extension/waves/tw_waves_extension.dart';
part 'src/extension/aeternity/tw_aeternity_extension.dart';
part 'src/extension/nebulas/tw_nebulas_extension.dart';
part 'src/extension/fio/tw_fio_extension.dart';
part 'src/extension/solana/tw_solana_extension.dart';
part 'src/extension/harmony/tw_harmony_extension.dart';
part 'src/extension/near/tw_near_extension.dart';
part 'src/extension/algorand/tw_algorand_extension.dart';
part 'src/extension/polkadot/tw_polkadot_extension.dart';
part 'src/extension/cardano/tw_cardano_extension.dart';
part 'src/extension/neo/tw_neo_extension.dart';
part 'src/extension/filecoin/tw_filecoin_extension.dart';
part 'src/extension/multivers_x/tw_multivers_x_extension.dart';
part 'src/extension/oasis/tw_oasis_extension.dart';
part 'src/extension/decred/tw_decred_extension.dart';
part 'src/extension/nervos/tw_nervos_extension.dart';
part 'src/extension/everscale/tw_everscale_extension.dart';
part 'src/extension/aptos/tw_aptos_extension.dart';
part 'src/extension/hedera/tw_hedera_extension.dart';
part 'src/extension/the_open_network/tw_the_open_network_extension.dart';
part 'src/extension/sui/tw_sui_extension.dart';
part 'src/extension/greenfield/tw_greenfield_extension.dart';
part 'src/extension/internet_computer/tw_internet_computer_extension.dart';
part 'src/extension/pactus/tw_pactus_extension.dart';
part 'src/extension/polymesh/tw_polymesh_extension.dart';
